export interface SeedCategory {
  name: string
  sort_order: number
  printer_type: 'kitchen' | 'bar' | 'billing'
}

export interface SeedItem {
  categoryName: string
  name: string
  price: number
  description?: string
  printer_type?: 'kitchen' | 'bar' | 'billing'
}

export const MENU_CATEGORIES: SeedCategory[] = [
  // Food categories (Kitchen)
  { name: 'VEG-APPETIZERS', sort_order: 1, printer_type: 'kitchen' },
  { name: 'NON VEG APPETIZERS', sort_order: 2, printer_type: 'kitchen' },
  { name: 'SOUP / FRESH SALAD', sort_order: 3, printer_type: 'kitchen' },
  { name: 'TANDOOR', sort_order: 4, printer_type: 'kitchen' },
  { name: 'PIZZA & PASTA', sort_order: 5, printer_type: 'kitchen' },
  { name: 'PASTA', sort_order: 6, printer_type: 'kitchen' },
  { name: 'THE DESI TABLE (MAINS)', sort_order: 7, printer_type: 'kitchen' },
  { name: 'THE GLOBAL TABLE (MAINS)', sort_order: 8, printer_type: 'kitchen' },
  { name: 'CHEF\'S SPECIAL - THAI CURRY', sort_order: 9, printer_type: 'kitchen' },
  { name: 'FRIED RICE / NOODLES', sort_order: 10, printer_type: 'kitchen' },
  { name: 'BURNT GARLIC RICE / NOODLES', sort_order: 11, printer_type: 'kitchen' },
  { name: 'SIDE BY SIDE ORDER', sort_order: 12, printer_type: 'kitchen' },
  { name: 'NACHOS & SOFT SHELL TACOS', sort_order: 13, printer_type: 'kitchen' },
  { name: 'BIRYANIS', sort_order: 14, printer_type: 'kitchen' },
  { name: 'DESSERT', sort_order: 15, printer_type: 'kitchen' },
  { name: 'BARBITES', sort_order: 16, printer_type: 'kitchen' },
  { name: 'BURGERS & TOASTS', sort_order: 17, printer_type: 'kitchen' },
  { name: 'BAO\'S AND DUMPLINGS', sort_order: 18, printer_type: 'kitchen' },
  { name: 'ALL ABOUT WINGS', sort_order: 19, printer_type: 'kitchen' },
  { name: 'WINGS IN BONE', sort_order: 20, printer_type: 'kitchen' },
  { name: 'BONELESS WINGS', sort_order: 21, printer_type: 'kitchen' },

  // Bar categories (Bar)
  { name: 'CLASSIC COCKTAILS', sort_order: 30, printer_type: 'bar' },
  { name: 'INVENTED COCKTAILS', sort_order: 31, printer_type: 'bar' },
  { name: 'BUILT TALL', sort_order: 32, printer_type: 'bar' },
  { name: 'SPARKLING COCKTAILS', sort_order: 33, printer_type: 'bar' },
  { name: 'SANGRIA', sort_order: 34, printer_type: 'bar' },
  { name: 'DRAUGHT BEER', sort_order: 35, printer_type: 'bar' },
  { name: 'BEERS & BREEZERS', sort_order: 36, printer_type: 'bar' },
  { name: 'WINE', sort_order: 37, printer_type: 'bar' },
  { name: 'LIQUEURS', sort_order: 38, printer_type: 'bar' },
  { name: 'TEQUILA (SHOTS)', sort_order: 39, printer_type: 'bar' },
  { name: 'SHOTS', sort_order: 40, printer_type: 'bar' },
  { name: 'MOCKTAILS', sort_order: 41, printer_type: 'bar' },
  { name: 'PREMIUM WHISKEY', sort_order: 42, printer_type: 'bar' },
  { name: 'IMPORTED WHISKEY', sort_order: 43, printer_type: 'bar' },
  { name: 'SINGLE MALT WHISKEY', sort_order: 44, printer_type: 'bar' },
  { name: 'VODKA', sort_order: 45, printer_type: 'bar' },
  { name: 'GIN', sort_order: 46, printer_type: 'bar' },
  { name: 'RUM AND BRANDY', sort_order: 47, printer_type: 'bar' },
  { name: 'SOFT BEVERAGES', sort_order: 48, printer_type: 'bar' }
]

export const MENU_ITEMS: SeedItem[] = [
  // VEG-APPETIZERS
  { categoryName: 'VEG-APPETIZERS', name: 'STUFF BAKED MUSHROOM', price: 400 },
  { categoryName: 'VEG-APPETIZERS', name: 'FALAFEL PITA POCKETS', price: 430 },
  { categoryName: 'VEG-APPETIZERS', name: 'FALAFEL WITH HUMMUS', price: 400 },
  { categoryName: 'VEG-APPETIZERS', name: 'THECHA COATED GRILLED PANEER', price: 430 },
  { categoryName: 'VEG-APPETIZERS', name: 'VEGGIE CROQUETTES', price: 420 },
  { categoryName: 'VEG-APPETIZERS', name: 'STIR SAUTED VEGETABLES', price: 420 },
  { categoryName: 'VEG-APPETIZERS', name: 'BUTTER GARLIC VEGITABLE', price: 430 },
  { categoryName: 'VEG-APPETIZERS', name: 'GHEE ROAST SOYA CHAP', price: 380 },
  { categoryName: 'VEG-APPETIZERS', name: 'GANTUR PANEER', price: 400 },
  { categoryName: 'VEG-APPETIZERS', name: 'ASIAN CHILLI MUSHROOM', price: 400 },
  { categoryName: 'VEG-APPETIZERS', name: 'JOIE', price: 450 },
  { categoryName: 'VEG-APPETIZERS', name: 'CLASSIC/GUNTUR PANEER CHILLI', price: 430 },
  { categoryName: 'VEG-APPETIZERS', name: 'PERI PERI PANEER SKEWARS', price: 450 },

  // NON VEG APPETIZERS
  { categoryName: 'NON VEG APPETIZERS', name: 'FISH FINGERS AND TATER SAUCE', price: 580 },
  { categoryName: 'NON VEG APPETIZERS', name: 'ORANGE GLAZE CHICKEN/ CHILLI CHICKEN', price: 430 },
  { categoryName: 'NON VEG APPETIZERS', name: 'SRIRACHA PRAWNS', price: 650 },
  { categoryName: 'NON VEG APPETIZERS', name: 'SALT AND PEPPER CHICKEN', price: 450 },
  { categoryName: 'NON VEG APPETIZERS', name: 'TAWA FISH', price: 630 },
  { categoryName: 'NON VEG APPETIZERS', name: 'GHEE ROAST PRAWNS', price: 650 },
  { categoryName: 'NON VEG APPETIZERS', name: 'GARLIC CHICKEN BAKED BITE BUN', price: 500, description: 'Tuscan garlic-infused chicken, oven-kissed, nestled in a golden, artisanal brioche.' },
  { categoryName: 'NON VEG APPETIZERS', name: 'LUDA', price: 450 },
  { categoryName: 'NON VEG APPETIZERS', name: 'BANG BANG CHICKEN', price: 480 },
  { categoryName: 'NON VEG APPETIZERS', name: 'PATRA FISH', price: 680 },
  { categoryName: 'NON VEG APPETIZERS', name: 'INDONESIAN CHICKEN SKEWARS', price: 480 },
  { categoryName: 'NON VEG APPETIZERS', name: 'ONE NIGHT IN PHUKET SPICY SHRIMP', price: 630 },
  { categoryName: 'NON VEG APPETIZERS', name: 'PERI PERI CHICKEN SKEWARS', price: 480 },
  { categoryName: 'NON VEG APPETIZERS', name: '4 YAAR CHICKEN', price: 500 },
  { categoryName: 'NON VEG APPETIZERS', name: 'LAWRENCE TAWA CHICKEN WITH KALA DARU', price: 480 },
  { categoryName: 'NON VEG APPETIZERS', name: 'CHICKEN IN DA BASKET', price: 520 },
  { categoryName: 'NON VEG APPETIZERS', name: 'GUNTUR CHICKEN', price: 480 },
  { categoryName: 'NON VEG APPETIZERS', name: 'GOAN KING', price: 650 },
  { categoryName: 'NON VEG APPETIZERS', name: 'TIPSY LAMB', price: 700 },

  // SOUP / FRESH SALAD
  { categoryName: 'SOUP / FRESH SALAD', name: 'LEMON CORIANDER HOT BROTH (VEG)', price: 230 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'LEMON CORIANDER HOT BROTH (NON-VEG)', price: 280 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'ALMOND BROCCOLI SOUP (VEG)', price: 260 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'ALMOND BROCCOLI SOUP (CHICKEN)', price: 300 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'VEG MANCHOW SOUP', price: 230 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'CHICKEN MANCHOW SOUP', price: 280 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'CREAM OF TOMATO SOUP', price: 230 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'CREAM OF MUSHROOM SOUP', price: 280 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'CREAM OF BROCCOLI SOUP', price: 280 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'INSALATA CAESAR (VEG)', price: 320 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'INSALATA CAESAR (CHICKEN)', price: 370 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'INSALATA CAESAR (SHRIMP)', price: 420 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'AVOCADO SALAD (VEG)', price: 350 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'AVOCADO SALAD (CHICKEN)', price: 400 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'AVOCADO SALAD (SHRIMP)', price: 440 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'MEXICAN SALAD (VEG)', price: 320 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'MEXICAN SALAD (CHICKEN)', price: 370 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'MEXICAN SALAD (SHRIMP)', price: 440 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'GREEK SALAD (VEG)', price: 320 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'GREEK SALAD (CHICKEN)', price: 370 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'GREEK SALAD (SHRIMP)', price: 440 },
  { categoryName: 'SOUP / FRESH SALAD', name: 'APPLE WALNUT SALAD', price: 350 },

  // TANDOOR
  { categoryName: 'TANDOOR', name: 'PESHAWARI PANEER TIKKA / AFGHANI', price: 440 },
  { categoryName: 'TANDOOR', name: 'BHARWAN KUMBH KEBAB', price: 450 },
  { categoryName: 'TANDOOR', name: 'CLASSIC PANEER TIKKA', price: 430 },
  { categoryName: 'TANDOOR', name: 'SOYA CHAP TANDOORI KEBAB', price: 380 },
  { categoryName: 'TANDOOR', name: 'TANDOORI MUSHROOM', price: 400 },
  { categoryName: 'TANDOOR', name: 'CLAY OVEN ROASTED LOLLYPOP', price: 530 },
  { categoryName: 'TANDOOR', name: '8PM CHICKEN', price: 550 },
  { categoryName: 'TANDOOR', name: 'CILANTRO GARLIC CHICKEN TIKKA', price: 500 },
  { categoryName: 'TANDOOR', name: 'LANGDA CHICKEN', price: 550 },
  { categoryName: 'TANDOOR', name: 'CHEF\'S SPECIAL JWALA MURGH', price: 830, description: 'Luscious whole chicken marinated in chef\'s Maharashtrian GAVRAN style spicy masala & charcoal smoke topped with rum fire.' },
  { categoryName: 'TANDOOR', name: 'CHEFS MATKA CHICKEN', price: 480 },
  { categoryName: 'TANDOOR', name: 'SHIKHARI MURG (EXTRA SPICY)', price: 480, description: 'Chef special boneless chicken marinated overnight in full spicy shikari masala.' },
  { categoryName: 'TANDOOR', name: 'BHATTI DA MURG (HALF)', price: 500 },
  { categoryName: 'TANDOOR', name: 'BHATTI DA MURG (FULL)', price: 800 },
  { categoryName: 'TANDOOR', name: 'KAFIR LIME INFUSED KEBAB', price: 550 },
  { categoryName: 'TANDOOR', name: 'CAJUN TANDOORI JHINGA', price: 630 },
  { categoryName: 'TANDOOR', name: 'THE TIPPSY VEG PLATTER', price: 1250 },
  { categoryName: 'TANDOOR', name: 'THE TIPPSY NON VEG PLATTER', price: 1580 },

  // PIZZA & PASTA (Pizzas)
  { categoryName: 'PIZZA & PASTA', name: 'CLASSIC MARGHERITA PIZZA', price: 400 },
  { categoryName: 'PIZZA & PASTA', name: 'TANDOORI VEG PIZZA', price: 450, description: 'Savor a vibrant Tandoori Veg Pizza, a symphony of spiced vegetables and smoky flavors.' },
  { categoryName: 'PIZZA & PASTA', name: 'CHEESY BLAST PIZZA', price: 460, description: 'Four types of cheese, cheese lovers must try, yummy' },
  { categoryName: 'PIZZA & PASTA', name: 'FULL HOUSE EXOTIC PIZZA', price: 460, description: 'All types of exotic vegetable and mozzarella cheese, cheese sauce' },
  { categoryName: 'PIZZA & PASTA', name: 'JAMAICAN PANEER PIZZA', price: 550, description: 'Jamaican garlic paneer, three bell pepper, olives, cheese' },
  { categoryName: 'PIZZA & PASTA', name: 'SPICY PERI PERI COTTAGE CHEESE PIZZA', price: 550 },
  { categoryName: 'PIZZA & PASTA', name: 'CHICKEN OVERLOAD CHICKEN PIZZA', price: 600 },
  { categoryName: 'PIZZA & PASTA', name: 'JAMAICAN GARLIC CHICKEN PIZZA', price: 520 },
  { categoryName: 'PIZZA & PASTA', name: 'CHICKEN PEPPERONI PIZZA', price: 550 },
  { categoryName: 'PIZZA & PASTA', name: 'SEA FOOD PIZZA', price: 680 },
  { categoryName: 'PIZZA & PASTA', name: 'LASSONI CHICKEN PIZZA', price: 520 },
  { categoryName: 'PIZZA & PASTA', name: 'MUTTON ROGAN PIZZA', price: 700 },
  { categoryName: 'PIZZA & PASTA', name: 'LAAL MIRCH CHICKEN PIZZA', price: 520 },
  { categoryName: 'PIZZA & PASTA', name: 'MEXICAN VEGGIE NAANZA', price: 400 },
  { categoryName: 'PIZZA & PASTA', name: 'PANEER MAKHANI NAANZA', price: 400 },
  { categoryName: 'PIZZA & PASTA', name: 'KOLHAPURI CHICKEN KHEEMA NAANZA', price: 450 },
  { categoryName: 'PIZZA & PASTA', name: 'MAKHAN CHICKEN NAANZA', price: 450 },

  // PASTA
  { categoryName: 'PASTA', name: 'VEG CRUST CANNELLONI', price: 480 },
  { categoryName: 'PASTA', name: 'CHEF\'S SPECIAL EXOTIC VEG LASAGNE', price: 530 },
  { categoryName: 'PASTA', name: 'PENNE PASTA - VEG', price: 400, description: 'Choice of Napolitan, Alfredo, or Pink Sauce' },
  { categoryName: 'PASTA', name: 'PENNE PASTA - CHICKEN', price: 450, description: 'Choice of Napolitan, Alfredo, or Pink Sauce' },
  { categoryName: 'PASTA', name: 'SPAGHETTI AGLIO OLIO / CREAMY ALFREDO (VEG)', price: 480 },
  { categoryName: 'PASTA', name: 'SPAGHETTI AGLIO OLIO / CREAMY ALFREDO (CHICKEN)', price: 520 },
  { categoryName: 'PASTA', name: 'CHEF\'S SPECIAL CHICKEN BOLOGNESE LASAGNE', price: 580 },
  { categoryName: 'PASTA', name: 'CHEF\'S SPECIAL CHICKEN BOLOGNESE PENNE', price: 480 },
  { categoryName: 'PASTA', name: 'CHEF\'S SPECIAL CHICKEN BOLOGNESE SPAGHETTI', price: 500 },
  { categoryName: 'PASTA', name: 'POLLO PEPPERY MAC & CHEESE', price: 480 },
  { categoryName: 'PASTA', name: 'PASTA AL PESTO - VEG', price: 480, description: 'Red Chilli, Basil, or Cilantro Pesto' },
  { categoryName: 'PASTA', name: 'PASTA AL PESTO - CHICKEN', price: 520, description: 'Red Chilli, Basil, or Cilantro Pesto' },
  { categoryName: 'PASTA', name: 'KOLHAPURI CHICKEN / BUTTER CHICKEN CANNELLONI', price: 580 },
  { categoryName: 'PASTA', name: 'PASTA BARBARESCA', price: 420 },
  { categoryName: 'PASTA', name: 'CHICKEN SPAGHETTI AGLIO OLIO', price: 420 },
  { categoryName: 'PASTA', name: 'CHICKEN SPAGHETTI CREAMY ALFREDO', price: 480 },

  // THE DESI TABLE (MAINS)
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'MALABAR GREEN CURRY', price: 400 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'VEG JALFREZZI', price: 430 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'TIPPSY PANEER KHUMAS', price: 480, description: 'Paneer medallions in rich cashew-tomato gravy, served with biryani rice.' },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'PANEER BUTTER MASALA', price: 450 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'PANEER TIKKA MASALA', price: 430 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'VEG DEEVANI', price: 400 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'VILAYATI SABZI', price: 450 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'TAWA SAJI', price: 400 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'CHEFS SPECIAL MURGH KHUMAS', price: 580, description: 'Chicken keema in Indian gravy with half tandoori chicken & biryani rice.' },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'GAVRAN STYLE CHICKEN RASSA', price: 480 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'BUTTER CHICKEN', price: 480 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'CHICKEN CHETTINAD', price: 480 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'MUTTON CHETTINAD', price: 680 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'MUTTON ROGAN JOSH', price: 680 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'CHICKEN KALA RASSA', price: 480 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'MUTTON KALA RASSA', price: 680 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'CHICKEN RA RA', price: 500 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'MUTTON RA RA', price: 700 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'GOAN/MALVANI FISH CURRY', price: 680 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'MACHAR ZOL', price: 550 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'DAL FRY', price: 300 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'DAL TADKA', price: 350 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'DAL PALAK', price: 350 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'MA KI DAAL', price: 400 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'DESI GHEE DAL KHICHADI', price: 320 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'CHICKEN DAL KHICHADI', price: 450 },
  { categoryName: 'THE DESI TABLE (MAINS)', name: 'MUTTON DAL KHICHADI', price: 550 },

  // THE GLOBAL TABLE (MAINS)
  { categoryName: 'THE GLOBAL TABLE (MAINS)', name: 'BURMESE KHOW SUEY VEG', price: 520 },
  { categoryName: 'THE GLOBAL TABLE (MAINS)', name: 'BURMESE KHOW SUEY CHICKEN', price: 550 },

  // CHEF'S SPECIAL - THAI CURRY
  { categoryName: 'CHEF\'S SPECIAL - THAI CURRY', name: 'THAI CURRY RED/GREEN - VEGETABLE', price: 520 },
  { categoryName: 'CHEF\'S SPECIAL - THAI CURRY', name: 'THAI CURRY RED/GREEN - CHICKEN', price: 570 },
  { categoryName: 'CHEF\'S SPECIAL - THAI CURRY', name: 'THAI CURRY RED/GREEN - PRAWN', price: 650 },
  { categoryName: 'CHEF\'S SPECIAL - THAI CURRY', name: 'PAD THAI VEG', price: 520 },
  { categoryName: 'CHEF\'S SPECIAL - THAI CURRY', name: 'PAD THAI SEAFOOD', price: 650 },
  { categoryName: 'CHEF\'S SPECIAL - THAI CURRY', name: 'GRILLED FISH WITH DEMIGLAZE SAUCE', price: 520 },
  { categoryName: 'CHEF\'S SPECIAL - THAI CURRY', name: 'CHICKEN ROULADE', price: 500 },
  { categoryName: 'CHEF\'S SPECIAL - THAI CURRY', name: 'HERB CRUSTED CHICKEN', price: 490 },
  { categoryName: 'CHEF\'S SPECIAL - THAI CURRY', name: 'CAJUN PRAWNS', price: 650 },
  { categoryName: 'CHEF\'S SPECIAL - THAI CURRY', name: 'MINTY THYME LAMB STEAK', price: 700 },

  // FRIED RICE / NOODLES
  { categoryName: 'FRIED RICE / NOODLES', name: 'FRIED RICE VEGETABLE', price: 330 },
  { categoryName: 'FRIED RICE / NOODLES', name: 'FRIED RICE CHICKEN', price: 380 },
  { categoryName: 'FRIED RICE / NOODLES', name: 'FRIED RICE SEA FOOD', price: 450 },
  { categoryName: 'FRIED RICE / NOODLES', name: 'CHILLI GARLIC NOODELS', price: 400 },
  { categoryName: 'FRIED RICE / NOODLES', name: 'TRIPPLE VEG FRIED RICE', price: 350 },
  { categoryName: 'FRIED RICE / NOODLES', name: 'TRIPPLE NON VEG FRIED RICE', price: 400 },

  // BURNT GARLIC RICE / NOODLES
  { categoryName: 'BURNT GARLIC RICE / NOODLES', name: 'BURNT GARLIC RICE/NOODLES VEG', price: 350 },
  { categoryName: 'BURNT GARLIC RICE / NOODLES', name: 'BURNT GARLIC RICE/NOODLES CHICKEN', price: 400 },

  // SIDE BY SIDE ORDER
  { categoryName: 'SIDE BY SIDE ORDER', name: 'ROTI', price: 60 },
  { categoryName: 'SIDE BY SIDE ORDER', name: 'MAKHAN ROTI', price: 70 },
  { categoryName: 'SIDE BY SIDE ORDER', name: 'NAAN', price: 80 },
  { categoryName: 'SIDE BY SIDE ORDER', name: 'MAKHAN NAAN', price: 90 },
  { categoryName: 'SIDE BY SIDE ORDER', name: 'BUTTER GARLIC NAAN', price: 120 },
  { categoryName: 'SIDE BY SIDE ORDER', name: 'BUTTER CHEESE GARLIC NAAN', price: 150 },
  { categoryName: 'SIDE BY SIDE ORDER', name: 'STEAMED RICE', price: 120 },
  { categoryName: 'SIDE BY SIDE ORDER', name: 'JEERA RICE', price: 120 },

  // NACHOS & SOFT SHELL TACOS
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'CRUST CHEESY NACHOS', price: 380 },
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'NACHOS WITH SALSA', price: 330 },
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'GHEE ROST CHICKEN NACHOS', price: 420 },
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'LOADED BEANS NACHOS VEG', price: 380 },
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'LOADED BEANS NACHOS CHICKEN', price: 400 },
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'MANHATTAN NACHOS', price: 400 },
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'LOADED BBQ CHICKEN NACHOS', price: 430 },
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'BUTTER CHICKEN TACOS', price: 430 },
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'KOLHAPURI CHICKEN TACOS', price: 430 },
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'CHICKEN STRIPES NACHOS', price: 450 },
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'CFS PRWANS NACHOS', price: 510 },
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'AFGHANI TACOS VEG', price: 400 },
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'AFGHANI TACOS CHICKEN', price: 430 },
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'HARABHARA TACOS', price: 410 },
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'CAJUN PANEER TACOS', price: 430 },
  { categoryName: 'NACHOS & SOFT SHELL TACOS', name: 'CREAMY VEG TACOS', price: 410 },

  // BIRYANIS
  { categoryName: 'BIRYANIS', name: 'MUGHLAI CHICKEN BIRYANI', price: 490 },
  { categoryName: 'BIRYANIS', name: 'MATKKA CHICKEN DUM BIRYANI', price: 540 },
  { categoryName: 'BIRYANIS', name: 'PRAWNS BIRYANI', price: 620 },
  { categoryName: 'BIRYANIS', name: 'MUTTON DUM BIRYANI', price: 650 },
  { categoryName: 'BIRYANIS', name: 'MUGHLAI VEG BIRYANI', price: 450 },
  { categoryName: 'BIRYANIS', name: 'MATKA VEG BIRYANI', price: 460 },

  // DESSERT
  { categoryName: 'DESSERT', name: 'HOT CHOCOLATE SIZZLING BROWNIE WITH ICE CREAM', price: 310 },
  { categoryName: 'DESSERT', name: 'PANNA COTTA', price: 350 },
  { categoryName: 'DESSERT', name: 'MISSISSIPPI MUD PIE', price: 350 },
  { categoryName: 'DESSERT', name: 'BURNT BASQUE CHEESE CAKE', price: 400 },
  { categoryName: 'DESSERT', name: 'TIRAMISU', price: 350 },
  { categoryName: 'DESSERT', name: 'MOONG DAL CIGAR ROLL', price: 350 },
  { categoryName: 'DESSERT', name: 'TRES LECHES', price: 420 },
  { categoryName: 'DESSERT', name: 'SHAHI TUKDA', price: 300 },

  // BARBITES
  { categoryName: 'BARBITES', name: 'CHANA JOR GARAM', price: 120 },
  { categoryName: 'BARBITES', name: 'MASLEDAR DAANE', price: 120 },
  { categoryName: 'BARBITES', name: 'BOILLED CORN CHAT', price: 120 },
  { categoryName: 'BARBITES', name: 'NACHANI PAPAD', price: 80 },
  { categoryName: 'BARBITES', name: 'MASALA NACHANI PAPAD', price: 120 },
  { categoryName: 'BARBITES', name: 'CLASSIC MASALA PAPAD', price: 100 },
  { categoryName: 'BARBITES', name: 'POTATO STRIPS BOWL', price: 220 },
  { categoryName: 'BARBITES', name: 'POTATO WEDGES SALTED', price: 220 },
  { categoryName: 'BARBITES', name: 'POTATO WEDGES PERI-PERI', price: 250 },
  { categoryName: 'BARBITES', name: 'CAJUN CRUMB ONION RING', price: 260 },
  { categoryName: 'BARBITES', name: 'BEER BATTERD ONION RINGS', price: 300 },
  { categoryName: 'BARBITES', name: 'BIRD PEPPER CHILI CORN', price: 360 },
  { categoryName: 'BARBITES', name: 'THECHA COATED GRILLED PANEER (BARBITE)', price: 420 },
  { categoryName: 'BARBITES', name: 'JALAPEÑO CHEESE BALLS', price: 390 },
  { categoryName: 'BARBITES', name: 'CHICKEN POPCORN', price: 420 },
  { categoryName: 'BARBITES', name: 'MUSHROOM BROCCOLI STIRED FRY', price: 350 },
  { categoryName: 'BARBITES', name: 'NAL STOP ANDA BHURJEE', price: 300 },
  { categoryName: 'BARBITES', name: 'BOILLED EGG BHURJEE', price: 350 },
  { categoryName: 'BARBITES', name: 'KHEEMA PAV', price: 500 },
  { categoryName: 'BARBITES', name: 'ASSORTED PAKODA', price: 250 },
  { categoryName: 'BARBITES', name: 'THE TIPPSY BITES PLATTER (FOUR SORTS)', price: 520 },

  // BURGERS & TOASTS
  { categoryName: 'BURGERS & TOASTS', name: 'SMASHED BURGER VEG', price: 360 },
  { categoryName: 'BURGERS & TOASTS', name: 'SMASHED BURGER CHICKEN', price: 450 },
  { categoryName: 'BURGERS & TOASTS', name: 'CLASSIC VEG BURGER', price: 350 },
  { categoryName: 'BURGERS & TOASTS', name: 'COTTAGE CHEESE PERI PERI BURGER', price: 350 },
  { categoryName: 'BURGERS & TOASTS', name: 'ALOO TIKKI BURGER', price: 300 },
  { categoryName: 'BURGERS & TOASTS', name: 'BEAST BURGER', price: 400 },
  { categoryName: 'BURGERS & TOASTS', name: 'CHICKEN BOMBER BURGER', price: 420 },
  { categoryName: 'BURGERS & TOASTS', name: 'VEGGIE BOMBER BURGER', price: 380 },
  { categoryName: 'BURGERS & TOASTS', name: 'CRISPY FRIED CHICKEN BURGER', price: 430 },
  { categoryName: 'BURGERS & TOASTS', name: 'SPICY GHOST ON TOAST', price: 400 },
  { categoryName: 'BURGERS & TOASTS', name: 'AVACADO TOAST', price: 320 },
  { categoryName: 'BURGERS & TOASTS', name: 'BRUESCHETTA', price: 320 },
  { categoryName: 'BURGERS & TOASTS', name: 'CHEESE CHILLY TOAST', price: 280 },
  { categoryName: 'BURGERS & TOASTS', name: 'GARLIC COTTAGE CHEESE BAKED BITE BUN', price: 480 },
  { categoryName: 'BURGERS & TOASTS', name: 'GARLIC CHICKEN BAKED BITE BUN', price: 500 },
  { categoryName: 'BURGERS & TOASTS', name: 'MUSHROOM BRUESCHETTA', price: 320 },
  { categoryName: 'BURGERS & TOASTS', name: 'CHICKEN BRUESCHETTA', price: 320 },
  { categoryName: 'BURGERS & TOASTS', name: 'CHEESY CHICKEN ON TOAST', price: 300 },

  // BAO'S AND DUMPLINGS
  { categoryName: 'BAO\'S AND DUMPLINGS', name: 'CHA SU PANEER BAO', price: 400 },
  { categoryName: 'BAO\'S AND DUMPLINGS', name: 'ASIAN EXOTIC VEGETABLE BAO', price: 350 },
  { categoryName: 'BAO\'S AND DUMPLINGS', name: 'CHA SU CHICKEN BAO', price: 400 },
  { categoryName: 'BAO\'S AND DUMPLINGS', name: 'ASIAN CHICKEN BAO', price: 450 },
  { categoryName: 'BAO\'S AND DUMPLINGS', name: 'FISH TALE BAO', price: 480 },
  { categoryName: 'BAO\'S AND DUMPLINGS', name: 'BEETROOT DUMPLING', price: 320 },
  { categoryName: 'BAO\'S AND DUMPLINGS', name: 'VEG DUMPLING', price: 320 },
  { categoryName: 'BAO\'S AND DUMPLINGS', name: 'CHICKEN DUMPLING', price: 350 },

  // WINGS IN BONE
  { categoryName: 'WINGS IN BONE', name: 'WINGS IN BONE - SMOKY BBQ', price: 400 },
  { categoryName: 'WINGS IN BONE', name: 'WINGS IN BONE - PERI PERI', price: 420 },
  { categoryName: 'WINGS IN BONE', name: 'WINGS IN BONE - BUFFALO HOT', price: 450 },

  // BONELESS WINGS
  { categoryName: 'BONELESS WINGS', name: 'BONELESS WINGS - SMOKY BBQ', price: 400 },
  { categoryName: 'BONELESS WINGS', name: 'BONELESS WINGS - PERI PERI', price: 420 },
  { categoryName: 'BONELESS WINGS', name: 'BONELESS WINGS - BUFFALO HOT', price: 450 },
  { categoryName: 'BONELESS WINGS', name: 'CHANCHAL CHICKEN WINGS', price: 450 },
  { categoryName: 'BONELESS WINGS', name: 'TRISHA CHICKEN WINGS', price: 450 },

  // CLASSIC COCKTAILS
  { categoryName: 'CLASSIC COCKTAILS', name: 'GIMLET', price: 420, description: 'GIN, LIME, SUGAR' },
  { categoryName: 'CLASSIC COCKTAILS', name: 'COSMOPOLITAN', price: 420, description: 'VODKA, CRANBERRY, TRIPLE SEC, LIME' },
  { categoryName: 'CLASSIC COCKTAILS', name: 'MAI TAI', price: 420, description: 'WHITE RUM, DARK RUM, PINEAPPLE, ORANGE, LIME' },
  { categoryName: 'CLASSIC COCKTAILS', name: 'CLASSIC HOT TODY', price: 420, description: 'BRANDY, HONEY, INDIAN SPICES' },
  { categoryName: 'CLASSIC COCKTAILS', name: 'BLOODY MARRY', price: 420, description: 'VODKA, TOMATO, PEPPER, HERBS' },
  { categoryName: 'CLASSIC COCKTAILS', name: 'MARGARITA', price: 420, description: 'TEQUILA, ORANGE LIQUEUR, LIME' },
  { categoryName: 'CLASSIC COCKTAILS', name: 'CAIPIROSKA', price: 420, description: 'VODKA, MINT, LIME' },
  { categoryName: 'CLASSIC COCKTAILS', name: 'MOJITO', price: 420, description: 'WHITE RUM, MINT, LIME' },
  { categoryName: 'CLASSIC COCKTAILS', name: 'WHISKEY SOUR', price: 420, description: 'WHISKEY, EGG WHITE, LIME' },
  { categoryName: 'CLASSIC COCKTAILS', name: 'MUD SLIDE', price: 650, description: 'VODKA, BAILEYS, KAHLUA, CHOCOLATE SAUCE, CREAM' },
  { categoryName: 'CLASSIC COCKTAILS', name: 'OLD FASHIONED', price: 420 },
  { categoryName: 'CLASSIC COCKTAILS', name: 'WHISKEY HIGHBALL', price: 420 },
  { categoryName: 'CLASSIC COCKTAILS', name: 'BLACK RUSSIAN', price: 500 },
  { categoryName: 'CLASSIC COCKTAILS', name: 'WHITE RUSSIAN', price: 500 },
  { categoryName: 'CLASSIC COCKTAILS', name: 'PALOMA (CLASSIC)', price: 500, description: 'TEQUILA, GRAPE FRUIT, LIME, MAPLE SYRUP' },

  // INVENTED COCKTAILS
  { categoryName: 'INVENTED COCKTAILS', name: 'BARMANS KETTLES', price: 850, description: 'ASK FOR FLAVOURS' },
  { categoryName: 'INVENTED COCKTAILS', name: 'BARMANS SECRET', price: 550, description: 'ASK OUR BARTENDERS' },
  { categoryName: 'INVENTED COCKTAILS', name: 'ELIXIER OF TIPSY', price: 500, description: 'PINEAPPLE JUICE, WHISKEY, STRAWBERRY, EGGWHITE, LIME' },
  { categoryName: 'INVENTED COCKTAILS', name: 'SANTAIGO TINI', price: 500, description: 'WHITE RUM, VODKA, POMEGRANATE, LIME' },
  { categoryName: 'INVENTED COCKTAILS', name: 'BEAUTY LADY', price: 500, description: 'VODKA, GRENADINE, ORANGE, LIME' },
  { categoryName: 'INVENTED COCKTAILS', name: 'SEXY SMILE', price: 500, description: 'VODKA, WHISKEY, BEER, CREAM, EGG WHITE, BASIL.' },
  { categoryName: 'INVENTED COCKTAILS', name: 'CUCCUMBER TWIST', price: 500, description: 'GIN, CORIANDER, CUCUMBER, BEER' },
  { categoryName: 'INVENTED COCKTAILS', name: 'SINGAPORE SILLING', price: 500, description: 'GIN, LIME, CUCUMBER, ROSEMARY, BLUEBERRY, TONIC WATER' },
  { categoryName: 'INVENTED COCKTAILS', name: 'GIN FIZZ', price: 500, description: 'GIN, MAPLE SYRUP, LIME, EGGWHITE' },
  { categoryName: 'INVENTED COCKTAILS', name: 'PALOMA (INVENTED)', price: 500, description: 'TEQUILA, GRAPE FRUIT, LIME, MAPLE SYRUP' },
  { categoryName: 'INVENTED COCKTAILS', name: 'KAFFIR RUM', price: 500, description: 'RUM, ORANGE, LIME, KAFFIR LIME' },
  { categoryName: 'INVENTED COCKTAILS', name: 'DRUNKEN MARGARITA', price: 500, description: 'TEQUILA, ORANGE LIQUEUR, LIME, RED WINE' },
  { categoryName: 'INVENTED COCKTAILS', name: 'MELON WIVES', price: 500, description: 'WHITE RUM, BASIL, SWEET & SOUR, FRESH WATERMELON' },
  { categoryName: 'INVENTED COCKTAILS', name: 'CAFÉ-TINI', price: 550, description: 'VODKA, KAHLUA, COFFEE, VANILLA, BAILEYS' },
  { categoryName: 'INVENTED COCKTAILS', name: 'flaming lambourginee', price: 1000 },
  { categoryName: 'INVENTED COCKTAILS', name: 'Zombie', price: 550 },
  { categoryName: 'INVENTED COCKTAILS', name: 'God Mother', price: 550 },
  { categoryName: 'INVENTED COCKTAILS', name: 'Brave Bull', price: 550 },
  { categoryName: 'INVENTED COCKTAILS', name: 'BANANA DAIQUIRI', price: 550 },
  { categoryName: 'INVENTED COCKTAILS', name: 'PASSENGER PRINCESS', price: 550 },
  { categoryName: 'INVENTED COCKTAILS', name: 'BAHAMA MAMA', price: 550 },
  { categoryName: 'INVENTED COCKTAILS', name: 'PAINKILLER', price: 550 },
  { categoryName: 'INVENTED COCKTAILS', name: 'THE LAST WORD', price: 600 },
  { categoryName: 'INVENTED COCKTAILS', name: '100 WAYS TO LIE', price: 600 },

  // BUILT TALL
  { categoryName: 'BUILT TALL', name: 'CLASSIC LIIT GLASS', price: 700 },
  { categoryName: 'BUILT TALL', name: 'CLASSIC LIIT PITCHER', price: 1950 },
  { categoryName: 'BUILT TALL', name: 'GILLIGANS LIIT GLASS', price: 700 },
  { categoryName: 'BUILT TALL', name: 'GILLIGANS LIIT PITCHER', price: 1950 },
  { categoryName: 'BUILT TALL', name: 'ADIOS MUDDAFUCKER GLASS', price: 700 },
  { categoryName: 'BUILT TALL', name: 'ADIOS MUDDAFUCKER PITCHER', price: 1950 },
  { categoryName: 'BUILT TALL', name: 'BLUE FROG GLASS', price: 750 },
  { categoryName: 'BUILT TALL', name: 'BLUE FROG PITCHER', price: 2000 },
  { categoryName: 'BUILT TALL', name: 'SEX WITH SATAN GLASS', price: 750 },
  { categoryName: 'BUILT TALL', name: 'SEX WITH SATAN PITCHER', price: 2000 },
  { categoryName: 'BUILT TALL', name: 'CALL A TAXI GLASS', price: 750 },
  { categoryName: 'BUILT TALL', name: 'CALL A TAXI PITCHER', price: 2000 },

  // SPARKLING COCKTAILS
  { categoryName: 'SPARKLING COCKTAILS', name: 'BELLINI', price: 450 },
  { categoryName: 'SPARKLING COCKTAILS', name: 'FRENCH 75', price: 450 },
  { categoryName: 'SPARKLING COCKTAILS', name: 'MIMOSA', price: 450 },
  { categoryName: 'SPARKLING COCKTAILS', name: 'BROKEN NEGRONI', price: 450 },

  // SANGRIA
  { categoryName: 'SANGRIA', name: 'CLASSIC SANGRIA (RED/WHITE) GLASS', price: 490 },
  { categoryName: 'SANGRIA', name: 'CLASSIC SANGRIA (RED/WHITE) PITCHER', price: 2150 },
  { categoryName: 'SANGRIA', name: 'BASIL APPLE SANGRIA (WHITE) GLASS', price: 490 },
  { categoryName: 'SANGRIA', name: 'BASIL APPLE SANGRIA (WHITE) PITCHER', price: 2150 },
  { categoryName: 'SANGRIA', name: 'ROSEBERRY SANGRIA (RED) GLASS', price: 490 },
  { categoryName: 'SANGRIA', name: 'ROSEBERRY SANGRIA (RED) PITCHER', price: 2150 },
  { categoryName: 'SANGRIA', name: 'WATERMELON SANGRIA (WHITE) GLASS', price: 490 },
  { categoryName: 'SANGRIA', name: 'WATERMELON SANGRIA (WHITE) PITCHER', price: 2150 },

  // DRAUGHT BEER
  { categoryName: 'DRAUGHT BEER', name: 'KINGFISHER GLASS', price: 230 },
  { categoryName: 'DRAUGHT BEER', name: 'KINGFISHER PITCHER', price: 950 },
  { categoryName: 'DRAUGHT BEER', name: 'KINGFISHER TOWER', price: 1700 },
  { categoryName: 'DRAUGHT BEER', name: 'KINGFISHER ULTRA GLASS', price: 280 },
  { categoryName: 'DRAUGHT BEER', name: 'KINGFISHER ULTRA PITCHER', price: 1150 },
  { categoryName: 'DRAUGHT BEER', name: 'KINGFISHER ULTRA TOWER', price: 2100 },
  { categoryName: 'DRAUGHT BEER', name: 'KINGFISHER ULTRA MAX GLASS', price: 310 },
  { categoryName: 'DRAUGHT BEER', name: 'KINGFISHER ULTRA MAX PITCHER', price: 1400 },
  { categoryName: 'DRAUGHT BEER', name: 'KINGFISHER ULTRA MAX TOWER', price: 2750 },
  { categoryName: 'DRAUGHT BEER', name: 'HEINEKEN GLASS', price: 310 },
  { categoryName: 'DRAUGHT BEER', name: 'HEINEKEN PITCHER', price: 1400 },
  { categoryName: 'DRAUGHT BEER', name: 'HEINEKEN TOWER', price: 2750 },

  // BEERS & BREEZERS
  { categoryName: 'BEERS & BREEZERS', name: 'KINGFISHER PINT', price: 240 },
  { categoryName: 'BEERS & BREEZERS', name: 'KINGFISHER ULTRA PINT', price: 300 },
  { categoryName: 'BEERS & BREEZERS', name: 'KINGFISHER ULTRA MAX PINT', price: 320 },
  { categoryName: 'BEERS & BREEZERS', name: 'CORONA PINT', price: 400 },
  { categoryName: 'BEERS & BREEZERS', name: 'HOEGAARDEN PINT', price: 350 },
  { categoryName: 'BEERS & BREEZERS', name: 'BUDWEISER PINT', price: 330 },
  { categoryName: 'BEERS & BREEZERS', name: 'BUDWEISER MAGNUM PINT', price: 350 },
  { categoryName: 'BEERS & BREEZERS', name: 'CARLSBERG ELEPHANT PINT', price: 350 },
  { categoryName: 'BEERS & BREEZERS', name: 'CARLSBERG PINT', price: 330 },
  { categoryName: 'BEERS & BREEZERS', name: 'HEINEKEN/SILVER PINT', price: 320 },
  { categoryName: 'BEERS & BREEZERS', name: 'BREEZER Cranberry', price: 290 },
  { categoryName: 'BEERS & BREEZERS', name: 'BREEZER Jamaican', price: 290 },
  { categoryName: 'BEERS & BREEZERS', name: 'BREEZER Blueberry', price: 290 },
  { categoryName: 'BEERS & BREEZERS', name: 'BREEZER Lemon', price: 290 },
  { categoryName: 'BEERS & BREEZERS', name: 'BREEZER Blackberry', price: 290 },

  // WINE
  { categoryName: 'WINE', name: 'RED-Sula Cabernet Shiraz GLASS', price: 445 },
  { categoryName: 'WINE', name: 'RED-Sula Satori GLASS', price: 445 },
  { categoryName: 'WINE', name: 'WHITE-Jacobs Creek Chardonnay GLASS', price: 750 },
  { categoryName: 'WINE', name: 'WHITE-Sula Chenin Blanc GLASS', price: 445 },
  { categoryName: 'WINE', name: 'WHITE-Sula Riesling GLASS', price: 445 },
  { categoryName: 'WINE', name: 'WHITE-Sula Suavignon Blanc GLASS', price: 445 },
  { categoryName: 'WINE', name: 'SPARKLING-Chandon Brut GLASS', price: 655 },
  { categoryName: 'WINE', name: 'RED-Jacobs Creek Shiraz GLASS', price: 750 },
  { categoryName: 'WINE', name: 'RED-Sula Dindori Shiraz GLASS', price: 445 },

  // LIQUEURS
  { categoryName: 'LIQUEURS', name: 'KAHLUA', price: 380 },
  { categoryName: 'LIQUEURS', name: 'SAMBUCA', price: 380 },
  { categoryName: 'LIQUEURS', name: 'BAILEYS IRISH CREAM', price: 450 },
  { categoryName: 'LIQUEURS', name: 'JAGERMIESTER', price: 495 },

  // TEQUILA (SHOTS)
  { categoryName: 'TEQUILA (SHOTS)', name: 'La Chica Silver SHOT', price: 300 },
  { categoryName: 'TEQUILA (SHOTS)', name: 'La Chica Gold SHOT', price: 350 },
  { categoryName: 'TEQUILA (SHOTS)', name: 'Don Alejenadro SHOT', price: 400 },

  // SHOTS
  { categoryName: 'SHOTS', name: 'B 52', price: 450 },
  { categoryName: 'SHOTS', name: 'ACID DANCER', price: 450 },
  { categoryName: 'SHOTS', name: 'KAMAKAZI', price: 350 },
  { categoryName: 'SHOTS', name: 'GRENADE', price: 850 },
  { categoryName: 'SHOTS', name: 'CINAMON WHISKEY', price: 399 },
  { categoryName: 'SHOTS', name: 'JAGER BOMB', price: 650 },
  { categoryName: 'SHOTS', name: 'zombie brain', price: 550 },

  // MOCKTAILS
  { categoryName: 'MOCKTAILS', name: 'FRESH FOUR FRUITS', price: 350, description: 'LIME, MINT, FRESH FRUITS' },
  { categoryName: 'MOCKTAILS', name: 'GUAVA MARY', price: 350, description: 'GREEN CHILLI, GUAVA, LIME, SALT' },
  { categoryName: 'MOCKTAILS', name: 'KIWI KAFFIR LIME TWIST', price: 350, description: 'KIWI, KAFFIR LIME, LITCHI' },
  { categoryName: 'MOCKTAILS', name: 'RASPBERRY PIE', price: 350, description: 'RASPBERRY, LIME, MINT' },
  { categoryName: 'MOCKTAILS', name: 'ORANGE BLOSSOM', price: 350, description: 'ORANGE, LIME, PINEAPPLE, BASIL' },
  { categoryName: 'MOCKTAILS', name: 'SMOOTHIE - WATERMELON', price: 350 },
  { categoryName: 'MOCKTAILS', name: 'SMOOTHIE - BANANA', price: 350 },
  { categoryName: 'MOCKTAILS', name: 'SMOOTHIE - KIWI-STRAWBERRY', price: 350 },
  { categoryName: 'MOCKTAILS', name: 'SMOOTHIE - THREE BERRY', price: 350 },

  // PREMIUM WHISKEY
  { categoryName: 'PREMIUM WHISKEY', name: 'Oaksmith Gold 30ML', price: 160 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Oaksmith Gold 180ML', price: 850 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Oaksmith Gold 750ML', price: 3200 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Antiquity Blue 30ML', price: 155 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Antiquity Blue 180ML', price: 870 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Antiquity Blue 750ML', price: 3310 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Blenders Pride 30ML', price: 155 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Blenders Pride 180ML', price: 870 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Blenders Pride 750ML', price: 3310 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Blenders Pride Reserve 30ML', price: 165 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Blenders Pride Reserve 180ML', price: 890 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Blenders Pride Reserve 750ML', price: 3370 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Black & White 30ML', price: 280 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Black & White 180ML', price: 1580 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Black & White 750ML', price: 6150 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Royal Ranthambore 30ML', price: 280 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Royal Ranthambore 180ML', price: 1600 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Royal Ranthambore 750ML', price: 6000 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Vat 69 30ML', price: 250 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Vat 69 180ML', price: 1430 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Vat 69 750ML', price: 5100 },
  { categoryName: 'PREMIUM WHISKEY', name: 'J & B Rare 30ML', price: 230 },
  { categoryName: 'PREMIUM WHISKEY', name: 'J & B Rare 180ML', price: 1280 },
  { categoryName: 'PREMIUM WHISKEY', name: 'J & B Rare 750ML', price: 4800 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Black Dog 30ML', price: 280 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Black Dog 180ML', price: 1600 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Black Dog 750ML', price: 6000 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Dewars White Lable 30ML', price: 220 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Dewars White Lable 180ML', price: 1280 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Dewars White Lable 750ML', price: 4950 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Dewars 12 Years 30ML', price: 400 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Dewars 12 Years 180ML', price: 2300 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Dewars 12 Years 750ML', price: 8500 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Teachers Highland Cream 30ML', price: 280 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Teachers Highland Cream 180ML', price: 1600 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Teachers Highland Cream 750ML', price: 6000 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Teachers 50 30ML', price: 330 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Teachers 50 180ML', price: 1830 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Teachers 50 750ML', price: 7000 },
  { categoryName: 'PREMIUM WHISKEY', name: '100 Pipers 30ML', price: 280 },
  { categoryName: 'PREMIUM WHISKEY', name: '100 Pipers 180ML', price: 1600 },
  { categoryName: 'PREMIUM WHISKEY', name: '100 Pipers 750ML', price: 6000 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Willam Lawson 30ML', price: 180 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Willam Lawson 180ML', price: 1050 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Willam Lawson 750ML', price: 4100 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Black Dog 8 TRIPLE GOLD 30ML', price: 330 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Black Dog 8 TRIPLE GOLD 180ML', price: 1850 },
  { categoryName: 'PREMIUM WHISKEY', name: 'Black Dog 8 TRIPLE GOLD 750ML', price: 7000 },
  { categoryName: 'PREMIUM WHISKEY', name: 'ROCKFOLD 30ML', price: 250 },
  { categoryName: 'PREMIUM WHISKEY', name: 'ROCKFOLD 180ML', price: 1400 },
  { categoryName: 'PREMIUM WHISKEY', name: 'ROCKFOLD 750ML', price: 5200 },
  { categoryName: 'PREMIUM WHISKEY', name: 'GLENWALK 30ML', price: 250 },
  { categoryName: 'PREMIUM WHISKEY', name: 'GLENWALK 180ML', price: 1400 },
  { categoryName: 'PREMIUM WHISKEY', name: 'GLENWALK 750ML', price: 5200 },
  { categoryName: 'PREMIUM WHISKEY', name: 'SIGNATURE PREM 30ML', price: 165 },
  { categoryName: 'PREMIUM WHISKEY', name: 'SIGNATURE PREM 180ML', price: 890 },
  { categoryName: 'PREMIUM WHISKEY', name: 'SIGNATURE PREM 750ML', price: 3370 },

  // IMPORTED WHISKEY
  { categoryName: 'IMPORTED WHISKEY', name: 'Johnnie Walker Red Label 30ML', price: 250 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Johnnie Walker Red Label 180ML', price: 1400 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Johnnie Walker Red Label 750ML', price: 5200 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Johnnie Walker Black Label 30ML', price: 390 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Johnnie Walker Black Label 180ML', price: 2250 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Johnnie Walker Black Label 750ML', price: 8500 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Johnnie Walker Double Black 30ML', price: 490 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Johnnie Walker Double Black 180ML', price: 2800 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Johnnie Walker Double Black 750ML', price: 10500 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Chivas Regal 12 Yo 30ML', price: 390 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Chivas Regal 12 Yo 180ML', price: 2250 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Chivas Regal 12 Yo 750ML', price: 8500 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Ballentine 30ML', price: 250 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Ballentine 180ML', price: 1400 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Ballentine 750ML', price: 5200 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Jim Beam 30ML', price: 280 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Jim Beam 180ML', price: 1600 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Jim Beam 750ML', price: 6000 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Jameson Irish 30ML', price: 280 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Jameson Irish 180ML', price: 1600 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Jameson Irish 750ML', price: 6000 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Jack Daniels 30ML', price: 380 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Jack Daniels 180ML', price: 2150 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Jack Daniels 750ML', price: 8400 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Monkey Shoulder 30ML', price: 450 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Monkey Shoulder 180ML', price: 2600 },
  { categoryName: 'IMPORTED WHISKEY', name: 'Monkey Shoulder 750ML', price: 10000 },

  // SINGLE MALT WHISKEY
  { categoryName: 'SINGLE MALT WHISKEY', name: 'Indry 30ML', price: 500 },
  { categoryName: 'SINGLE MALT WHISKEY', name: 'Indry 180ML', price: 2850 },
  { categoryName: 'SINGLE MALT WHISKEY', name: 'Indry 750ML', price: 10700 },
  { categoryName: 'SINGLE MALT WHISKEY', name: 'Glenmorangie 10 Yo 30ML', price: 590 },
  { categoryName: 'SINGLE MALT WHISKEY', name: 'Glenmorangie 10 Yo 180ML', price: 3350 },
  { categoryName: 'SINGLE MALT WHISKEY', name: 'Glenmorangie 10 Yo 750ML', price: 12200 },
  { categoryName: 'SINGLE MALT WHISKEY', name: 'Glenlivet 12 Yo 30ML', price: 620 },
  { categoryName: 'SINGLE MALT WHISKEY', name: 'Glenlivet 12 Yo 180ML', price: 3500 },
  { categoryName: 'SINGLE MALT WHISKEY', name: 'Glenlivet 12 Yo 750ML', price: 12900 },
  { categoryName: 'SINGLE MALT WHISKEY', name: 'Glenfiddich 12 Yo 30ML', price: 650 },
  { categoryName: 'SINGLE MALT WHISKEY', name: 'Glenfiddich 12 Yo 180ML', price: 3800 },
  { categoryName: 'SINGLE MALT WHISKEY', name: 'Glenfiddich 12 Yo 750ML', price: 13110 },
  { categoryName: 'SINGLE MALT WHISKEY', name: 'Talisker 10 Yo 30ML', price: 690 },
  { categoryName: 'SINGLE MALT WHISKEY', name: 'Talisker 10 Yo 180ML', price: 3900 },
  { categoryName: 'SINGLE MALT WHISKEY', name: 'Talisker 10 Yo 750ML', price: 14200 },

  // VODKA
  { categoryName: 'VODKA', name: 'Smirnoff 30ML', price: 170 },
  { categoryName: 'VODKA', name: 'Smirnoff 180ML', price: 900 },
  { categoryName: 'VODKA', name: 'Smirnoff 750ML', price: 3200 },
  { categoryName: 'VODKA', name: 'Absolut 30ML', price: 260 },
  { categoryName: 'VODKA', name: 'Absolut 180ML', price: 1450 },
  { categoryName: 'VODKA', name: 'Absolut 750ML', price: 5200 },
  { categoryName: 'VODKA', name: 'Grey Goose 30ML', price: 490 },
  { categoryName: 'VODKA', name: 'Grey Goose 180ML', price: 2820 },
  { categoryName: 'VODKA', name: 'Grey Goose 750ML', price: 10800 },
  { categoryName: 'VODKA', name: 'Ciroc 30ML', price: 450 },
  { categoryName: 'VODKA', name: 'Ciroc 180ML', price: 2550 },
  { categoryName: 'VODKA', name: 'Ciroc 750ML', price: 9800 },
  { categoryName: 'VODKA', name: 'KETAL ONE 30ML', price: 250 },
  { categoryName: 'VODKA', name: 'KETAL ONE 180ML', price: 1430 },
  { categoryName: 'VODKA', name: 'KETAL ONE 750ML', price: 5100 },

  // GIN
  { categoryName: 'GIN', name: 'Hendricks 30ML', price: 480 },
  { categoryName: 'GIN', name: 'Hendricks 180ML', price: 2780 },
  { categoryName: 'GIN', name: 'Hendricks 750ML', price: 10500 },
  { categoryName: 'GIN', name: 'JAISALMER 30ML', price: 380 },
  { categoryName: 'GIN', name: 'JAISALMER 180ML', price: 2150 },
  { categoryName: 'GIN', name: 'JAISALMER 750ML', price: 8400 },
  { categoryName: 'GIN', name: 'Bombay Sapphire 30ML', price: 280 },
  { categoryName: 'GIN', name: 'Bombay Sapphire 180ML', price: 1600 },
  { categoryName: 'GIN', name: 'Bombay Sapphire 750ML', price: 6000 },
  { categoryName: 'GIN', name: 'Greater Than 30ML', price: 180 },
  { categoryName: 'GIN', name: 'Greater Than 180ML', price: 990 },
  { categoryName: 'GIN', name: 'Greater Than 750ML', price: 3700 },
  { categoryName: 'GIN', name: 'BLUE RIBBON 30ML', price: 110 },
  { categoryName: 'GIN', name: 'BLUE RIBBON 180ML', price: 580 },
  { categoryName: 'GIN', name: 'BLUE RIBBON 750ML', price: 2300 },

  // RUM AND BRANDY
  { categoryName: 'RUM AND BRANDY', name: 'Old Monk 30ML', price: 110 },
  { categoryName: 'RUM AND BRANDY', name: 'Old Monk 180ML', price: 580 },
  { categoryName: 'RUM AND BRANDY', name: 'Old Monk 750ML', price: 2300 },
  { categoryName: 'RUM AND BRANDY', name: 'Captain Morgon 30ML', price: 110 },
  { categoryName: 'RUM AND BRANDY', name: 'Captain Morgon 180ML', price: 580 },
  { categoryName: 'RUM AND BRANDY', name: 'Captain Morgon 750ML', price: 2300 },
  { categoryName: 'RUM AND BRANDY', name: 'Bacardi White 30ML', price: 170 },
  { categoryName: 'RUM AND BRANDY', name: 'Bacardi White 180ML', price: 900 },
  { categoryName: 'RUM AND BRANDY', name: 'Bacardi White 750ML', price: 3200 },
  { categoryName: 'RUM AND BRANDY', name: 'Bacardi Black 30ML', price: 115 },
  { categoryName: 'RUM AND BRANDY', name: 'Bacardi Black 180ML', price: 190 },
  { categoryName: 'RUM AND BRANDY', name: 'Bacardi Black 750ML', price: 2350 },
  { categoryName: 'RUM AND BRANDY', name: 'Honey Bee 30ML', price: 110 },
  { categoryName: 'RUM AND BRANDY', name: 'Honey Bee 180ML', price: 580 },
  { categoryName: 'RUM AND BRANDY', name: 'Honey Bee 750ML', price: 2300 },

  // SOFT BEVERAGES
  { categoryName: 'SOFT BEVERAGES', name: 'RED BULL', price: 250 },
  { categoryName: 'SOFT BEVERAGES', name: 'GINGER ALE/TONIC WATER', price: 200 },
  { categoryName: 'SOFT BEVERAGES', name: 'DIET COKE', price: 150 },
  { categoryName: 'SOFT BEVERAGES', name: 'FRUIT JUICE(PRESERVED)', price: 150 },
  { categoryName: 'SOFT BEVERAGES', name: 'ICED TEA LEMON/PEACH', price: 200 },
  { categoryName: 'SOFT BEVERAGES', name: 'FRESH LIME SODA/WATER', price: 130 },
  { categoryName: 'SOFT BEVERAGES', name: 'SOFT DRINK', price: 70 },
  { categoryName: 'SOFT BEVERAGES', name: 'SODA', price: 60 },
  { categoryName: 'SOFT BEVERAGES', name: 'BOTTLED WATER', price: 35 }
]
